import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from './context/ThemeContext'
import ClientThemeWrapper from './context/ClientThemeWrapper'
import { EdgeStoreProvider } from './lib/edgestore';
import { SessionProvider } from 'next-auth/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body  className={inter.className}>
      <EdgeStoreProvider>
        <ThemeProvider>
          <ClientThemeWrapper>
              {children}
          </ClientThemeWrapper>
        </ThemeProvider>
      </EdgeStoreProvider>
      </body>
    </html>
  )
}
